### PR TITLE
fix: wrap array to an obj in requester and unwrapped in responder

### PR DESCRIPTION
**Pull request by yamii**
Issue S-07385

### CODE REVIEW

**Comment by openam** [comment]
Should we update the Readme to reference rabbot instead of wascally?

**Comment by yamii** [comment]
@sydcanem @MarianneBorces please code review

**Comment by sydcanem** [comment]
I'm ok with this @yamii

**Comment by MarianneBorces** [comment]
👍

**Comment by rtorino** [comment]
💯

**Pull request merged**
