### PR TITLE
chore: update to @sinet/coding-convetions 2.x

### PR DESCRIPTION
**Pull request by MarianneBorces**
Closes [TK-09197](https://www12.v1host.com/SchoolImprovementNetwork47/Task.mvc/Summary?oidToken=Task%3A96552)

### CODE REVIEW

**Comment by MarianneBorces** [comment]
Hi @yamii and @sydcanem / @openam! can you guys take a look at my changes. Thanks!

**Comment by sydcanem** [comment]
Is this supposed to be a `chore` and not a `refactor`?

**Comment by MarianneBorces** [comment]
Done! @sydcanem

**Comment by openam** [comment]
Chore's are non-production code changes, e.g. grunt/gulp tasks, ci stuff, etc, https://github.com/School-Improvement-Network/coding-conventions/blob/master/git.md

**Pull request merged**
